denoise_fn_config:
  attention_resolutions:
  - 4
  base_channel: 64
  channel_multiplier:
  - 1
  - 2
  - 4
  - 8
  dims: 2
  dropout: 0.1
  head_channel: -1
  input_channel: 3
  num_heads: 4
  num_residual_blocks_of_a_block: 2
  use_new_attention_order: false